[package]
name = "gsnake"
version = "0.1.0"
authors = ["Graeme Hill <graemekh@gmail.com>"]

[dependencies]
gotham = "0.3"
gotham_derive = "0.3"
hyper = "0.12"
mime = "0.3"
serde = "1"
serde_derive = "1"
serde_json = "1"
